version: '3'

services:
  ansible:
    build:
      context: .
      dockerfile: ansible/Dockerfile
      args:
        ANSIBLE_VERSION: ${ANSIBLE_VERSION}
    container_name: ansible
    restart: unless-stopped